FROM python:3.11-slim

WORKDIR /app

# no need to buffer output when building the image
ENV PYTHONUNBUFFERED=1

# install poetry
RUN pip install --upgrade pip && \
    pip install poetry

# copy the poetry files
COPY pyproject.toml poetry.lock ./

# install dependencies
RUN poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

# copy the source code
COPY src/ .

# copy data for preloading -- demo only
COPY data/ .

CMD ["python", "api/main.py"]
